### ISSUE TITLE
Discord message unwanted embed

### ISSUE THREAD

**Issue by maxb2** [dungeon-revealer/dungeon-revealer#666]
Sometimes the automated discord messages have unwanted embeds.

This happens when the commit message includes a link. Using `<link>` suppresses the embed.

Relevant code:
```
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_UPDATES }}
        uses: Ilshidur/action-discord@759f6ea
        with:
          args: "New commit pushed, master@${{ env.COMMIT_SHORT }}: *${{ github.event.head_commit.message }}*\n <${{ github.event.head_commit.url }}>"

```
